// <auto-generated />
using FactoryService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FactoryService.Migrations
{
    [DbContext(typeof(DiagnoseContext))]
    [Migration("20220311112708_AddDB")]
    partial class AddDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiagnoseService.Model.Diagnoses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CarError")
                        .HasColumnType("bit");

                    b.Property<string>("CarSpeed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CommunicationError")
                        .HasColumnType("bit");

                    b.Property<bool>("CommunicationPowerError")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainerEmpty")
                        .HasColumnType("bit");

                    b.Property<string>("LED")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PLCFailure")
                        .HasColumnType("bit");

                    b.Property<bool>("Pause")
                        .HasColumnType("bit");

                    b.Property<bool>("System")
                        .HasColumnType("bit");

                    b.Property<bool>("WakeUp")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("diagnoses");
                });
#pragma warning restore 612, 618
        }
    }
}
